

# Project Name

**Project 07 — Lipinski Rule of Five Checker**

---

# Project Objective

একটি dataset-এর প্রতিটি molecule-এর জন্য Lipinski's Rule of Five check করা。

Output:

* Molecular Weight
* LogP
* H-Bond Donor
* H-Bond Acceptor
* Rule Violations
* Drug-Like (Yes / No)

---

# Project Workflow

```text
Load Dataset
      │
      ▼
Read SMILES
      │
      ▼
Convert SMILES → RDKit Molecule
      │
      ▼
Calculate Molecular Descriptors
      │
      ├──────── Molecular Weight
      │
      ├──────── LogP
      │
      ├──────── H-Bond Donor
      │
      └──────── H-Bond Acceptor
      │
      ▼
Apply Lipinski Rule
      │
      ▼
Count Violations
      │
      ▼
Drug-like Classification
      │
      ▼
Generate Final Report
```

---

# Notebook Structure

## Module 1 — Import Libraries

In [1]:
import pandas as pd

from rdkit import Chem
from rdkit.Chem import Descriptors
from rdkit.Chem import Lipinski

---

## Module 2 — Load Dataset

In [2]:
dataset_path = "../../dataset/molecules_100.csv"

df = pd.read_csv(dataset_path)

df.head()

      Name SMILES
0    Water      O
1  Methane      C
2   Ethane     CC
3  Propane    CCC
4   Butane   CCCC

---

## Module 3 — Convert SMILES

In [3]:
df["Mol"] = df["SMILES"].apply(Chem.MolFromSmiles)

df.head()

      Name SMILES                                                Mol
0    Water      O  <rdkit.Chem.rdchem.Mol object at 0x000001BBC31...
1  Methane      C  <rdkit.Chem.rdchem.Mol object at 0x000001BBC31...
2   Ethane     CC  <rdkit.Chem.rdchem.Mol object at 0x000001BBC31...
3  Propane    CCC  <rdkit.Chem.rdchem.Mol object at 0x000001BBC31...
4   Butane   CCCC  <rdkit.Chem.rdchem.Mol object at 0x000001BBC31...

---

## Module 4 — Calculate Molecular Weight

In [4]:
df["MolecularWeight"] = df["Mol"].apply(
    Descriptors.MolWt
)

df.head()

,Name,SMILES,Mol,MolecularWeight
0,Water,O,<rdkit.Chem.rdchem.Mol object at 0x000001BBC31...,18.015
1,Methane,C,<rdkit.Chem.rdchem.Mol object at 0x000001BBC31...,16.043
2,Ethane,CC,<rdkit.Chem.rdchem.Mol object at 0x000001BBC31...,30.070
3,Propane,CCC,<rdkit.Chem.rdchem.Mol object at 0x000001BBC31...,44.097
4,Butane,CCCC,<rdkit.Chem.rdchem.Mol object at 0x000001BBC31...,58.124

---

## Module 5 — Calculate LogP

In [5]:
df["LogP"] = df["Mol"].apply(
    Descriptors.MolLogP
)

df.head()

,Name,SMILES,Mol,MolecularWeight,LogP
0,Water,O,<rdkit.Chem.rdchem.Mol object at 0x000001BBC31...,18.015,-0.8247
1,Methane,C,<rdkit.Chem.rdchem.Mol object at 0x000001BBC31...,16.043,0.6361
2,Ethane,CC,<rdkit.Chem.rdchem.Mol object at 0x000001BBC31...,30.070,1.0262
3,Propane,CCC,<rdkit.Chem.rdchem.Mol object at 0x000001BBC31...,44.097,1.4163
4,Butane,CCCC,<rdkit.Chem.rdchem.Mol object at 0x000001BBC31...,58.124,1.8064

---

## Module 6 — Calculate Hydrogen Bond Donors

In [6]:
df["HBD"] = df["Mol"].apply(
    Lipinski.NumHDonors
)

df.head()

,Name,SMILES,Mol,MolecularWeight,LogP,HBD
0,Water,O,<rdkit.Chem.rdchem.Mol object at 0x000001BBC31...,18.015,-0.8247,0
1,Methane,C,<rdkit.Chem.rdchem.Mol object at 0x000001BBC31...,16.043,0.6361,0
2,Ethane,CC,<rdkit.Chem.rdchem.Mol object at 0x000001BBC31...,30.070,1.0262,0
3,Propane,CCC,<rdkit.Chem.rdchem.Mol object at 0x000001BBC31...,44.097,1.4163,0
4,Butane,CCCC,<rdkit.Chem.rdchem.Mol object at 0x000001BBC31...,58.124,1.8064,0

---

## Module 7 — Calculate Hydrogen Bond Acceptors

In [7]:
df["HBA"] = df["Mol"].apply(
    Lipinski.NumHAcceptors
)

df.head()

,Name,SMILES,Mol,MolecularWeight,LogP,HBD,HBA
0,Water,O,<rdkit.Chem.rdchem.Mol object at 0x000001BBC31...,18.015,-0.8247,0,0
1,Methane,C,<rdkit.Chem.rdchem.Mol object at 0x000001BBC31...,16.043,0.6361,0,0
2,Ethane,CC,<rdkit.Chem.rdchem.Mol object at 0x000001BBC31...,30.070,1.0262,0,0
3,Propane,CCC,<rdkit.Chem.rdchem.Mol object at 0x000001BBC31...,44.097,1.4163,0,0
4,Butane,CCCC,<rdkit.Chem.rdchem.Mol object at 0x000001BBC31...,58.124,1.8064,0,0

---

# Module 8 — Apply Lipinski Rule

In [8]:
def lipinski_rule(mol):

    mw = Descriptors.MolWt(mol)

    logp = Descriptors.MolLogP(mol)

    hbd = Lipinski.NumHDonors(mol)

    hba = Lipinski.NumHAcceptors(mol)

    violations = 0

    if mw > 500:
        violations += 1

    if logp > 5:
        violations += 1

    if hbd > 5:
        violations += 1

    if hba > 10:
        violations += 1

    return violations

---

## Module 9 — Count Violations

In [9]:
df["Violations"] = df["Mol"].apply(
    lipinski_rule
)

df.head()

,Name,SMILES,Mol,MolecularWeight,LogP,HBD,HBA,Violations
0,Water,O,<rdkit.Chem.rdchem.Mol object at 0x000001BBC31...,18.015,-0.8247,0,0,0
1,Methane,C,<rdkit.Chem.rdchem.Mol object at 0x000001BBC31...,16.043,0.6361,0,0,0
2,Ethane,CC,<rdkit.Chem.rdchem.Mol object at 0x000001BBC31...,30.070,1.0262,0,0,0
3,Propane,CCC,<rdkit.Chem.rdchem.Mol object at 0x000001BBC31...,44.097,1.4163,0,0,0
4,Butane,CCCC,<rdkit.Chem.rdchem.Mol object at 0x000001BBC31...,58.124,1.8064,0,0,0

---

## Module 10 — Drug-like Classification

In [10]:
df["DrugLike"] = df["Violations"].apply(
    lambda x: "Yes" if x <= 1 else "No"
)

df.head()

,Name,SMILES,Mol,MolecularWeight,LogP,HBD,HBA,Violations,DrugLike
0,Water,O,<rdkit.Chem.rdchem.Mol object at 0x000001BBC31...,18.015,-0.8247,0,0,0,Yes
1,Methane,C,<rdkit.Chem.rdchem.Mol object at 0x000001BBC31...,16.043,0.6361,0,0,0,Yes
2,Ethane,CC,<rdkit.Chem.rdchem.Mol object at 0x000001BBC31...,30.070,1.0262,0,0,0,Yes
3,Propane,CCC,<rdkit.Chem.rdchem.Mol object at 0x000001BBC31...,44.097,1.4163,0,0,0,Yes
4,Butane,CCCC,<rdkit.Chem.rdchem.Mol object at 0x000001BBC31...,58.124,1.8064,0,0,0,Yes

---

## Module 11 — Final Report

In [11]:
result = df[
    [
        "Name",
        "MolecularWeight",
        "LogP",
        "HBD",
        "HBA",
        "Violations",
        "DrugLike"
    ]
]

result

           Name  MolecularWeight    LogP  HBD  HBA  Violations DrugLike
0         Water           18.015 -0.8247    0    0           0      Yes
1       Methane           16.043  0.6361    0    0           0      Yes
2        Ethane           30.070  1.0262    0    0           0      Yes
3       Propane           44.097  1.4163    0    0           0      Yes
4        Butane           58.124  1.8064    0    0           0      Yes
..          ...              ...     ...  ...  ...         ...      ...
95  Paracetamol          151.165  1.3506    2    2           0      Yes
96    Ibuprofen          206.285  3.0732    1    1           0      Yes
97     Naproxen          230.263  3.0365    1    2           0      Yes
98    Lidocaine          248.370  3.0148    0    2           0      Yes
99     Nicotine          162.236  1.8483    0    2           0      Yes

[100 rows x 7 columns]

---

## Module 12 — Drug-like Molecules Only

In [12]:
drug_like = result[
    result["DrugLike"] == "Yes"
]

drug_like

           Name  MolecularWeight    LogP  HBD  HBA  Violations DrugLike
0         Water           18.015 -0.8247    0    0           0      Yes
1       Methane           16.043  0.6361    0    0           0      Yes
2        Ethane           30.070  1.0262    0    0           0      Yes
3       Propane           44.097  1.4163    0    0           0      Yes
4        Butane           58.124  1.8064    0    0           0      Yes
..          ...              ...     ...  ...  ...         ...      ...
95  Paracetamol          151.165  1.3506    2    2           0      Yes
96    Ibuprofen          206.285  3.0732    1    1           0      Yes
97     Naproxen          230.263  3.0365    1    2           0      Yes
98    Lidocaine          248.370  3.0148    0    2           0      Yes
99     Nicotine          162.236  1.8483    0    2           0      Yes

[99 rows x 7 columns]

## Module 13 — Non Drug-like Molecules

In [13]:
non_drug = result[
    result["DrugLike"] == "No"
]

non_drug

       Name  MolecularWeight    LogP  HBD  HBA  Violations DrugLike
91  Sucrose          356.324 -5.3547    8   11           2       No

---

## Module 14 — Summary Statistics

In [14]:
print("="*50)

print("Total Molecules :", len(df))

print("Drug-like :", len(drug_like))

print("Non Drug-like :", len(non_drug))

print("="*50)

==================================================
Total Molecules : 100
Drug-like : 99
Non Drug-like : 1
==================================================

# Concepts Covered

* SMILES Parsing
* Molecular Descriptors
* Molecular Weight (MW)
* LogP (Lipophilicity)
* Hydrogen Bond Donors (HBD)
* Hydrogen Bond Acceptors (HBA)
* Lipinski Rule of Five
* Drug-likeness Prediction
* Dataset Analysis
* Basic Drug Discovery Filtering

---

## Learning Outcome

After completing this notebook, you will be able to:

* Extract molecular descriptors using **RDKit**.
* Apply **Lipinski's Rule of Five** programmatically.
* Filter drug-like molecules from large molecular datasets.
* Implement the **first filtering step** of the drug discovery pipeline, including **QSAR, Virtual Screening, and Molecular Docking workflows**.